name: Sync Upstream
on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 12 点自动同步一次
  workflow_dispatch:      # 允许你手动点击按钮触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync upstream
        uses: a206b/upstream-sync@v2.0
        with:
          upstream_repository: huangxd-/danmu_api
          upstream_branch: main
          target_branch: main
          force: false # 如果你改动了代码，设为 false 避免覆盖你的修改
